import Head from 'next/head'
import Link from "next/link"
import Image from "next/image"
import type { NextPage } from 'next'
import React, { useEffect, useState } from 'react'
import { FaEdit, FaShare } from 'react-icons/fa'

import { Product } from '@/interfaces/product'
import { useAuth } from '@/context/AuthContext'
import { getFirebaseUser } from '@/slices/authSlice'
import { fetchProducts } from '@/services/products'
import NavBar from '@/components/navigation/main_navbar'
import ProfileFeed from '@/components/profile/profile_feed'
import SidebarRight from '@/components/sidebar/sidebar_right'

const Profile: NextPage = () => {
  const [products, setProducts] = useState<Product[]>([])
  const [loading, setLoading] = useState<boolean>(false)

  useEffect(() => {
    // fetch products
    const fetchProductsAndAlbums = async () => {
      setLoading(true)
      const [productsRes] = await Promise.all([
        fetchProducts(),
      ])
      setProducts(productsRes)
      //setAlbums(albumsRes)
      setLoading(false)
    }
    fetchProductsAndAlbums()

    return () => {
      //clean up hook
    }
  }, []);

  return (
    <>
      <Head>
        <title>User Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen md:h-screen">
        <NavBar />
        <div className="flex my-16">
          <div className="w-1/5 bg-gray-200">
            <SidebarRight />
          </div>
          <div className="w-4/5 bg-white">
            <div className="flex my-4">
              <div className="flex w-2/4">
                <Image className="rounded-full mx-5" src="/images/user.png" alt="" width="100" height="100" />
                <div className="flex-grow">
                  <Link href="/">
                    <h3 className="text-3xl font-bold text-gray-800">johndoe</h3>
                    <h3 className="text-2xl text-gray-800">John Doe</h3>
                  </Link>
                  <div className="flex items-center p-1 cursor-pointer" >
                    <button className="px-4 py-2 font-semibold text-medium bg-sky-500 text-white rounded-lg flex items-center">
                      <FaEdit className="mr-1" /> Edit profile
                    </button>
                  </div>
                </div>
              </div>
              <div className='w-2/4'>
                <FaShare />
              </div>
            </div>

            <div className="mx-2">
              <ul
                className="mb-5 flex list-none flex-row flex-wrap border-b-0 pl-0"
                role="tablist"
                data-te-nav-ref>
                <li role="presentation">
                  <a
                    href="#tabs-1"
                    className="my-2 block border-x-0 border-b-2 border-t-0 border-transparent px-7 pb-3.5 pt-4 text-xs font-medium uppercase leading-tight text-neutral-500 hover:isolate hover:border-transparent hover:bg-neutral-100 focus:isolate focus:border-transparent data-[te-nav-active]:border-neutral-800 data-[te-nav-active]:text-neutral-800 dark:text-neutral-400 dark:hover:bg-transparent dark:data-[te-nav-active]:border-neutral-600 dark:data-[te-nav-active]:text-neutral-600"
                    data-te-toggle="pill"
                    data-te-target="#tabs-1"
                    data-te-nav-active
                    role="tab"
                    aria-controls="tabs-1"
                    aria-selected="true"
                  >Videos</a>
                </li>
                <li role="presentation">
                  <a
                    href="#tabs-2"
                    className="my-2 block border-x-0 border-b-2 border-t-0 border-transparent px-7 pb-3.5 pt-4 text-xs font-medium uppercase leading-tight text-neutral-500 hover:isolate hover:border-transparent hover:bg-neutral-100 focus:isolate focus:border-transparent data-[te-nav-active]:border-neutral-800 data-[te-nav-active]:text-neutral-800 dark:text-neutral-400 dark:hover:bg-transparent dark:data-[te-nav-active]:border-neutral-600 dark:data-[te-nav-active]:text-neutral-600"
                    data-te-toggle="pill"
                    data-te-target="#tabs-2"
                    role="tab"
                    aria-controls="tabs-2"
                    aria-selected="false"
                  >Liked</a>
                </li>
              </ul>

              <div className="mb-6">
                <div
                  className="hidden opacity-100 transition-opacity duration-150 ease-linear data-[te-tab-active]:block"
                  id="tabs-1"
                  role="tabpanel"
                  aria-labelledby="tabs-tab1"
                  data-te-tab-active>
                  {/*<ProfileFeed products={products} />*/}
                </div>
                <div
                  className="hidden opacity-0 transition-opacity duration-150 ease-linear data-[te-tab-active]:block"
                  id="tabs-2"
                  role="tabpanel"
                  aria-labelledby="tabs-tab2">
                  
                </div>
              </div>

            </div>
          </div>
        </div>

      </main>
    </>
  );
};

export default Profile;
