import { useEffect, useState } from 'react'
import Head from "next/head"
import { Link } from 'react-router-dom'

import Loader from '../components/loader'
import { Product } from '../interfaces/product'
import { fetchProducts } from '../services/products'
import HomeFeed from "../components/feeds/home_feed"
import NavBar from "../components/navigation/main_navbar"
import SidebarLeft from '../components/sidebar/sidebar_left'
import SidebarRight from '../components/sidebar/sidebar_right'

const HomePage = () => {
  const [products, setProducts] = useState<Product[]>([])
  const [loading, setLoading] = useState<boolean>(false)

  useEffect(() => {
    // fetch products and their individual total album
    const fetchProductsAndAlbums = async () => {
      setLoading(true)
      const [productsRes] = await Promise.all([
        fetchProducts(),
      ])
      setProducts(productsRes)
      //setAlbums(albumsRes)
      setLoading(false)
    }
    fetchProductsAndAlbums()

    return () => {
      //clean up hook
    }
  }, []);

  return (
    <div className="">
      <Head>
        <title>VidShop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen md:h-screen">
        <NavBar />
        <div className="flex justify-center  my-16">
          <div className="hidden sm:block sm:w-1/4 bg-gray-200 h-screen">
            <SidebarLeft />
          </div>
          <div className="w-full sm:w-1/2 bg-gray-100 h-screen">
            <div className="max-w-md mx-auto sm:px-7 md:max-w-4xl md:px-2">
              <div className="pt-12 pageMargin sm:pt-16 md:pt-0">
                <section>
                  <HomeFeed products={products} />
                </section>
              </div>
            </div>
          </div>
          <div className="hidden sm:block sm:w-1/4 bg-gray-200 h-screen">
            <SidebarRight />
          </div>
        </div>
      </main>
    </div>
  )
}
export default HomePage