import Head from "next/head"
import { useRouter } from "next/router"
import { useEffect, lazy, useState } from "react"
import { useSession, getSession } from "next-auth/react"

import { useAuth } from "../context/AuthContext"
import NavBar from "../components/navigation/main_navbar"
import { setCredential, setFirebaseUser } from "../slices/authSlice"

const Home = () => {
  const { data: session } = useSession()
  const router = useRouter()
  const { currentUser } = useAuth()
  
  return (
    <div className="">
      <Head>
        <title>VidShop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen md:h-screen">
        <NavBar />
        <div className="px-2 text-xl font-bold text-center pt-28 text-shadow-md md:mr-0 md:pb-10 md:pt-36 md:text-xl lg:text-2xl 2xl:text-3xl">
          For You! | Fashion | Electronics | Beauty
        </div>
        <div className="max-w-md py-6 mx-auto sm:px-7 md:max-w-4xl md:px-2 md:py-10">

        </div>
      </main>
    </div>
  )
}

export default Home

export async function getServerSideProps({ req }: any) {
  const session = await getSession({ req })

  // if (!session) return { redirect: { destination: "/login", permanent: false } }

  return {
    props: { session },
  }
}
